### ISSUE TITLE
Unexpected lack of motion in example app

### ISSUE THREAD

**Issue by caioCrmall** [mrcendre/motion#1]
I tried to run the example but there is no motion to it.

**Comment by mrcendre** [comment]
@caioCrmall Thanks for the feedback ! 

Please file your issue with a bit more informations such as the environment in which you built and ran the example, what you expected and what was observed. You can also attach the output of `flutter doctor -v`.

Were you expecting gyroscope or pointer motion ? Is the gyroscope feature available on your device ?

**Comment by mrcendre** [comment]
Closing this issue as stale, feel free to reopen. Thank you !
